apiVersion: v1
kind: Secret
metadata:
  name:  my-secret
type: kubernetes.io/basic-auth
data: # dados codificados em base64 nos containers os valores serão decodificados e armazenados no filesystem
   username: YWRtaW4=
   password: bXktcGFzcy0xMjM=
stringData: # dados em texto plano
  password: mongodb
  username: admin

# basic-auth: - keys: username/password força o secret ter as keys username e passwordkubec
# ssh-auth: - keys: [user, pass] força o valor ser 'username:password'
# tls-auth: - tls certificates