apiVersion: v1
kind: Secret
metadata:
  name:  my-secret
data: # dados codificados em base64 nos containers os valores serão decodificados e armazenados no filesystem
   user: YWRtaW4=
   pass: bXktcGFzcy0xMjM=
stringData: # dados em texto plano
  my-database-name: mongodb

#type: Opaque - Default
# basic-auth: - keys: [user, pass] força o valor ser 'username/password'
# ssh-auth: - keys: [user, pass] força o valor ser 'username:password'
# tls-auth: - tls certificates