apiVersion: v1
kind: Service
metadata:
  name: svc-sts
spec:
  ports:
    - port: 80
  clusterIP: None # None, ClusterIP, LoadBalancer
  selector:
    app: nginx-app-pods

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sts
spec:
  podManagementPolicy: "orderedReady" # Define a ordem de criação dos pods [ "orderedReady", "Parallel" ]
  selector:
    matchLabels:
      app: nginx-app-pods
  serviceName: svc-sts # seleciona o service criado acima
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app-pods
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.23.1
          volumeMounts:
            - name: my-pv
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates: # cria um volume dinâmico
    - metadata:
        name: my-pv 
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi # Tamanho do volume