apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auditor-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "pods"] #deve ser minusculos e plural
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auditor-role-binding
  namespace: default
subjects:
  - kind: User
    name: auditor
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auditor-role

