apiVersion: v1
kind: Service
metadata:
  name: my-eps-service # Nome do service deve ser o mesmo do Endpoints
spec:
  ports:
    - name: http
      port: 80

---

apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-eps
  labels:
    kubernetes.io/service-name: my-eps-service
addressType: IPv4
endpoints:
  - addresses:
    - 172.17.0.4 #pod-apache
ports:
  - name: http
    port: 80
    protocol: TCP

---

apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-eps-2
  labels:
    kubernetes.io/service-name: my-eps-service
addressType: IPv4
endpoints:
  - addresses:
    - 172.17.0.3 #pod-nginx
ports:
  - name: http
    port: 80
    protocol: TCP