apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-container
    image: redis
    resources:
      limits:
        cpu: "500m"
        memory: "100Mi"
    volumeMounts:
    - name: "cach-storage"
      mountPath: "/my-volume"
  
  volumes:
  - name: cach-storage
    hostPah:
      path: "/my-volume/2-persistent"
    # emptyDir: {}
