apiVersion: v1
kind: Endpoints
metadata:
  name: my-endpoints-service
subsets:
  - addresses:
      - ip: 77.68.88.76 #IIS
      # - ip: 172.17.0.4 #pod-apache
      # - ip:  172.17.0.3 #pod-nginx
    ports: 
      - port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-endpoints-service # Nome do service deve ser o mesmo do Endpoints
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
