apiVersion: v1
kind: Secret
metadata:
  name:  my-secret
data: # dados codificados em base64 nos containers os valores serão decodificados e armazenados no filesystem
   user: YWRtaW4=
   pass: bXktcGFzcy0xMjM=
stringData: # dados em texto plano
  my-database-name: mongodb

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-vol-env
  labels:
    app: app-java
spec:
  containers:
  - name: mycontainer
    image: nginx
    envFrom: # Cria variaveis de ambiente a partir do secret
    - secretRef: 
        name: my-secret
        optional: true # Se o secret nao existir, o container nao falha
    volumeMounts:
      - name: my-vol
        mountPath: /etc/my-vol
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

  volumes:
  - name: my-vol
    secret:
      secretName: my-secret
      optional: true # Se o secret nao existir, o volume nao falha